### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ryanlo713** [svsdval/video2midi#55]
```
python .\v2m.py output.mp4
pygame 2.6.0 (SDL 2.28.4, Python 3.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
open file [output_.mp4]
Traceback (most recent call last):
  File ".\v2m.py", line 75, in <module>
    from video2midi.midi import *
  File "\video2midi-master\video2midi\midi.py", line 6, in <module>
    class midinotes:
  File "\video2midi-master\video2midi\midi.py", line 42, in midinotes
    def save_to_disk(self, filename: str) -> tuple[int, str]:
TypeError: 'type' object is not subscriptable
```

**Comment by C0rn3j** [comment]
You need to use a supported Python version, 3.9 at minimum.

**Comment by svsdval** [comment]
Or you can download older version, 4.8/4.7 works fine ;)
https://github.com/svsdval/video2midi/releases
